name: apple-clang

on:
  push:
    branches:
      - "develop"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    branches:
      - "develop"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  build:
    name: ci_macos-latest_clang_${{ matrix.lib }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        lib:
          - static
          - shared

    steps:
      # ----------------------------
      # Checkout
      # ----------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------
      # Install ccache
      # ----------------------------
      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2

      # ----------------------------
      # Install dependencies
      # ----------------------------
      - name: Install dependencies
        run: |
          brew install \
            cmake \
            ninja

      # ----------------------------
      # Select compiler
      # ----------------------------
      - name: Select compiler
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      # ----------------------------
      # Configure
      # ----------------------------
      - name: Configure
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DFAKER_BUILD_SHARED:BOOL=${{ matrix.lib == 'shared' && 'ON' || 'OFF' }} \
            -DFAKER_BUILD_EXAMPLE:BOOL=OFF \
            -DFAKER_BUILD_TESTS:BOOL=ON \
            -DFAKER_CODE_COVERAGE:BOOL=OFF

      # ----------------------------
      # Build
      # ----------------------------
      - name: Build
        run: cmake --build build

      # ----------------------------
      # Test
      # ----------------------------
      - name: Test
        run: ctest --test-dir build --output-on-failure

      # ----------------------------
      # Install check
      # ----------------------------
      - name: Install
        run: cmake --install build --prefix install
